Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -22,38 +22,71 @@ jobs:
           MYSQL_DATABASE: test_db
           MYSQL_USER: user
           MYSQL_PASSWORD: passw0rd
+
+      working_directory: ~/textboox  #自身のアプリディレクトリ名を設定  
+
+
     steps:
-# テストを実行
-      - checkout
-      - run:
-      # Our primary container isn’t MYSQL so run a sleep command until it’s ready.
-          name: MySQL が準備できるまで待機
-          command: |
-            for i in `seq 1 10`;
-            do
-              nc -z 127.0.0.1 3306 && echo Success && exit 0
-              echo -n .
-              sleep 1
-            done
-            echo Failed waiting for MySQL && exit 1
-      - run:
-          name: docker-compose build
-          command: docker-compose build
-      # - run:
-      #     name: create network
-      #     command: docker network create textboox-network
-      - run:
-          name: restart
-          command: docker-compose up -d
-      # Database setup
-      - run: docker-compose exec web sh -c 'bundle exec rake db:create'
-      - run: docker-compose exec web sh -c 'bundle exec rake db:schema:load'
-      - run:
-          name: test
-          command: docker-compose exec web sh -c 'bundle exec rspec'
-      - run:
-          name: docker-compose down
-          command: docker-compose down
+    - checkout
+
+    - restore_cache:
+        keys:
+        - v1-dependencies-{{ checksum "Gemfile.lock" }}
+        - v1-dependencies-
+
+    - run:
+        name: install dependencies
+        command: |
+          gem install bundler -v 2.0.2
+          bundle install --jobs=4 --retry=3 --path vendor/bundle
+
+    - save_cache:
+        paths:
+        - ./vendor/bundle
+        key: v1-dependencies-{{ checksum "Gemfile.lock" }}
+
+    # Database setup
+    - run: mv ./config/database.yml.ci ./config/database.yml
+
+    # Database setup
+    - run:
+        name: Databasesetup
+        command: |
+           bundle exec rake db:create
+           bundle exec rake db:schema:load
+
+#     steps:
+# # テストを実行
+#       - checkout
+#       - run:
+#       # Our primary container isn’t MYSQL so run a sleep command until it’s ready.
+#           name: MySQL が準備できるまで待機
+#           command: |
+#             for i in `seq 1 10`;
+#             do
+#               nc -z 127.0.0.1 3306 && echo Success && exit 0
+#               echo -n .
+#               sleep 1
+#             done
+#             echo Failed waiting for MySQL && exit 1
+#       - run:
+#           name: docker-compose build
+#           command: docker-compose build
+#       # - run:
+#       #     name: create network
+#       #     command: docker network create textboox-network
+#       - run:
+#           name: restart
+#           command: docker-compose up -d
+#       # Database setup
+#       - run: docker-compose exec web sh -c 'bundle exec rake db:create'
+#       - run: docker-compose exec web sh -c 'bundle exec rake db:schema:load'
+#       - run:
+#           name: test
+#           command: docker-compose exec web sh -c 'bundle exec rspec'
+#       - run:
+#           name: docker-compose down
+#           command: docker-compose down
 # EC2にSSH接続し、デプロイを実行
   deploy:
     machine:
